### ISSUE TITLE
SyntaxError: from __future__ imports must occur at the beginning of the file

### ISSUE THREAD

**Issue by seungjaeryanlee** [microsoft/logrl#1]
Following the README to run LogDQN on Atari Asterix, I got the following error:

```
Traceback (most recent call last):
  File "/home/rlee/anaconda3/envs/logrl/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/rlee/anaconda3/envs/logrl/lib/python3.6/runpy.py", line 153, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/rlee/git/logrl/log_dqn_experiments/log_dqn/train_atari.py", line 26
    from __future__ import absolute_import
    ^
SyntaxError: from __future__ imports must occur at the beginning of the file
```

**Comment by seungjaeryanlee** [comment]
Found the reason: this because there are two docstrings before the future import. These three files have the problem:
- circular_replay_buffer_64.py
- log_dqn_agent.py
- train_atari.py

Simply removing one of the docstrings for each file worked.

**Comment by fatemi** [comment]
Thanks. Fixed.
